from __future__ import annotations

from datetime import date, datetime, time
from decimal import Decimal

from pydantic import BaseModel, EmailStr, Field, field_validator, model_validator

from app.schemas.common import ORMModel

# Salary is monetary so we want exactly 2 decimal places — represented
# as Decimal end-to-end (NEVER float) to avoid silent precision loss.
# Values are non-negative and bounded so a typo can't accidentally
# write a 50-digit "salary".
_SALARY_MAX = Decimal("99999999999.99")  # matches Numeric(12, 2)


class EmployeeBase(BaseModel):
    # employee_code is server-generated by default. Clients can still
    # supply one (e.g. importing from another HR system); when omitted
    # the service mints `EMP-NNNNNN` from the new row's id.
    employee_code: str | None = Field(default=None, min_length=1, max_length=64)
    name: str = Field(min_length=1, max_length=128)
    designation: str = Field(min_length=1, max_length=128)
    company: str = Field(min_length=1, max_length=128)
    dob: date | None = None
    email: EmailStr | None = None
    phone: str | None = Field(default=None, max_length=32)
    department: str | None = Field(default=None, max_length=128)
    join_date: date | None = None
    salary_package: Decimal | None = Field(default=None, ge=0, le=_SALARY_MAX, decimal_places=2)
    shift_start: time | None = None
    shift_end: time | None = None

    @field_validator("salary_package")
    @classmethod
    def _quantize_salary(cls, v: Decimal | None) -> Decimal | None:
        # Quantize to exactly 2 dp so JSON in/out is stable. We accept
        # any precision on input (e.g. "50000" or "50000.5") and snap
        # it to 2 dp deterministically.
        if v is None:
            return v
        return v.quantize(Decimal("0.01"))

    @model_validator(mode="after")
    def _validate_shift_window(self):
        # Either both endpoints set or neither. A half-set window is
        # almost always a UI bug — better to surface than to silently
        # store a meaningless value.
        if (self.shift_start is None) != (self.shift_end is None):
            raise ValueError("shift_start and shift_end must both be set or both be omitted")
        # We do NOT enforce shift_end > shift_start — overnight shifts
        # (e.g. 22:00 → 06:00) are legitimate and the consumer renders
        # them correctly.
        return self


class EmployeeCreate(EmployeeBase):
    is_active: bool = True


class EmployeeUpdate(BaseModel):
    name: str | None = Field(default=None, min_length=1, max_length=128)
    designation: str | None = Field(default=None, min_length=1, max_length=128)
    company: str | None = Field(default=None, min_length=1, max_length=128)
    dob: date | None = None
    email: EmailStr | None = None
    phone: str | None = Field(default=None, max_length=32)
    department: str | None = Field(default=None, max_length=128)
    join_date: date | None = None
    salary_package: Decimal | None = Field(default=None, ge=0, le=_SALARY_MAX, decimal_places=2)
    shift_start: time | None = None
    shift_end: time | None = None
    is_active: bool | None = None

    @field_validator("salary_package")
    @classmethod
    def _quantize_salary(cls, v: Decimal | None) -> Decimal | None:
        if v is None:
            return v
        return v.quantize(Decimal("0.01"))


class EmployeeRead(ORMModel):
    id: int
    employee_code: str
    name: str
    email: str | None
    phone: str | None
    designation: str | None
    department: str | None
    company: str | None
    dob: date | None
    join_date: date | None
    salary_package: Decimal | None
    shift_start: time | None
    shift_end: time | None
    # `image_path` is internal storage detail; clients consume the
    # photo via `GET /employees/{id}/image`. `has_image` is a derived
    # flag (Employee.has_image @property) so the UI knows when to
    # render the avatar without us leaking the server file layout.
    has_image: bool
    is_active: bool
    created_at: datetime
    updated_at: datetime
