/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login.index'
import { Route as LoginHrRouteImport } from './routes/login.hr'
import { Route as LoginAdminRouteImport } from './routes/login.admin'
import { Route as DashboardUnknownFacesRouteImport } from './routes/_dashboard.unknown-faces'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard.settings'
import { Route as DashboardRequestsRouteImport } from './routes/_dashboard.requests'
import { Route as DashboardReportsRouteImport } from './routes/_dashboard.reports'
import { Route as DashboardPresenceRouteImport } from './routes/_dashboard.presence'
import { Route as DashboardHomeRouteImport } from './routes/_dashboard.home'
import { Route as DashboardFaceTrainingRouteImport } from './routes/_dashboard.face-training'
import { Route as DashboardEmployeesRouteImport } from './routes/_dashboard.employees'
import { Route as DashboardCamerasRouteImport } from './routes/_dashboard.cameras'
import { Route as DashboardAlertsRouteImport } from './routes/_dashboard.alerts'
import { Route as DashboardAdminRouteImport } from './routes/_dashboard.admin'
import { Route as DashboardCamerasIndexRouteImport } from './routes/_dashboard.cameras.index'
import { Route as DashboardCamerasLiveRouteImport } from './routes/_dashboard.cameras.live'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRoute,
} as any)
const LoginHrRoute = LoginHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => LoginRoute,
} as any)
const LoginAdminRoute = LoginAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LoginRoute,
} as any)
const DashboardUnknownFacesRoute = DashboardUnknownFacesRouteImport.update({
  id: '/unknown-faces',
  path: '/unknown-faces',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRequestsRoute = DashboardRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPresenceRoute = DashboardPresenceRouteImport.update({
  id: '/presence',
  path: '/presence',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHomeRoute = DashboardHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFaceTrainingRoute = DashboardFaceTrainingRouteImport.update({
  id: '/face-training',
  path: '/face-training',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEmployeesRoute = DashboardEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCamerasRoute = DashboardCamerasRouteImport.update({
  id: '/cameras',
  path: '/cameras',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAlertsRoute = DashboardAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCamerasIndexRoute = DashboardCamerasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardCamerasRoute,
} as any)
const DashboardCamerasLiveRoute = DashboardCamerasLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => DashboardCamerasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRouteWithChildren
  '/admin': typeof DashboardAdminRoute
  '/alerts': typeof DashboardAlertsRoute
  '/cameras': typeof DashboardCamerasRouteWithChildren
  '/employees': typeof DashboardEmployeesRoute
  '/face-training': typeof DashboardFaceTrainingRoute
  '/home': typeof DashboardHomeRoute
  '/presence': typeof DashboardPresenceRoute
  '/reports': typeof DashboardReportsRoute
  '/requests': typeof DashboardRequestsRoute
  '/settings': typeof DashboardSettingsRoute
  '/unknown-faces': typeof DashboardUnknownFacesRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/hr': typeof LoginHrRoute
  '/login/': typeof LoginIndexRoute
  '/cameras/live': typeof DashboardCamerasLiveRoute
  '/cameras/': typeof DashboardCamerasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof DashboardAdminRoute
  '/alerts': typeof DashboardAlertsRoute
  '/employees': typeof DashboardEmployeesRoute
  '/face-training': typeof DashboardFaceTrainingRoute
  '/home': typeof DashboardHomeRoute
  '/presence': typeof DashboardPresenceRoute
  '/reports': typeof DashboardReportsRoute
  '/requests': typeof DashboardRequestsRoute
  '/settings': typeof DashboardSettingsRoute
  '/unknown-faces': typeof DashboardUnknownFacesRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/hr': typeof LoginHrRoute
  '/login': typeof LoginIndexRoute
  '/cameras/live': typeof DashboardCamerasLiveRoute
  '/cameras': typeof DashboardCamerasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/_dashboard/admin': typeof DashboardAdminRoute
  '/_dashboard/alerts': typeof DashboardAlertsRoute
  '/_dashboard/cameras': typeof DashboardCamerasRouteWithChildren
  '/_dashboard/employees': typeof DashboardEmployeesRoute
  '/_dashboard/face-training': typeof DashboardFaceTrainingRoute
  '/_dashboard/home': typeof DashboardHomeRoute
  '/_dashboard/presence': typeof DashboardPresenceRoute
  '/_dashboard/reports': typeof DashboardReportsRoute
  '/_dashboard/requests': typeof DashboardRequestsRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/_dashboard/unknown-faces': typeof DashboardUnknownFacesRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/hr': typeof LoginHrRoute
  '/login/': typeof LoginIndexRoute
  '/_dashboard/cameras/live': typeof DashboardCamerasLiveRoute
  '/_dashboard/cameras/': typeof DashboardCamerasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/alerts'
    | '/cameras'
    | '/employees'
    | '/face-training'
    | '/home'
    | '/presence'
    | '/reports'
    | '/requests'
    | '/settings'
    | '/unknown-faces'
    | '/login/admin'
    | '/login/hr'
    | '/login/'
    | '/cameras/live'
    | '/cameras/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/alerts'
    | '/employees'
    | '/face-training'
    | '/home'
    | '/presence'
    | '/reports'
    | '/requests'
    | '/settings'
    | '/unknown-faces'
    | '/login/admin'
    | '/login/hr'
    | '/login'
    | '/cameras/live'
    | '/cameras'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/login'
    | '/_dashboard/admin'
    | '/_dashboard/alerts'
    | '/_dashboard/cameras'
    | '/_dashboard/employees'
    | '/_dashboard/face-training'
    | '/_dashboard/home'
    | '/_dashboard/presence'
    | '/_dashboard/reports'
    | '/_dashboard/requests'
    | '/_dashboard/settings'
    | '/_dashboard/unknown-faces'
    | '/login/admin'
    | '/login/hr'
    | '/login/'
    | '/_dashboard/cameras/live'
    | '/_dashboard/cameras/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof LoginRoute
    }
    '/login/hr': {
      id: '/login/hr'
      path: '/hr'
      fullPath: '/login/hr'
      preLoaderRoute: typeof LoginHrRouteImport
      parentRoute: typeof LoginRoute
    }
    '/login/admin': {
      id: '/login/admin'
      path: '/admin'
      fullPath: '/login/admin'
      preLoaderRoute: typeof LoginAdminRouteImport
      parentRoute: typeof LoginRoute
    }
    '/_dashboard/unknown-faces': {
      id: '/_dashboard/unknown-faces'
      path: '/unknown-faces'
      fullPath: '/unknown-faces'
      preLoaderRoute: typeof DashboardUnknownFacesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/requests': {
      id: '/_dashboard/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof DashboardRequestsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/reports': {
      id: '/_dashboard/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/presence': {
      id: '/_dashboard/presence'
      path: '/presence'
      fullPath: '/presence'
      preLoaderRoute: typeof DashboardPresenceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/home': {
      id: '/_dashboard/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof DashboardHomeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/face-training': {
      id: '/_dashboard/face-training'
      path: '/face-training'
      fullPath: '/face-training'
      preLoaderRoute: typeof DashboardFaceTrainingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/employees': {
      id: '/_dashboard/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof DashboardEmployeesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/cameras': {
      id: '/_dashboard/cameras'
      path: '/cameras'
      fullPath: '/cameras'
      preLoaderRoute: typeof DashboardCamerasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/alerts': {
      id: '/_dashboard/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof DashboardAlertsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin': {
      id: '/_dashboard/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/cameras/': {
      id: '/_dashboard/cameras/'
      path: '/'
      fullPath: '/cameras/'
      preLoaderRoute: typeof DashboardCamerasIndexRouteImport
      parentRoute: typeof DashboardCamerasRoute
    }
    '/_dashboard/cameras/live': {
      id: '/_dashboard/cameras/live'
      path: '/live'
      fullPath: '/cameras/live'
      preLoaderRoute: typeof DashboardCamerasLiveRouteImport
      parentRoute: typeof DashboardCamerasRoute
    }
  }
}

interface DashboardCamerasRouteChildren {
  DashboardCamerasLiveRoute: typeof DashboardCamerasLiveRoute
  DashboardCamerasIndexRoute: typeof DashboardCamerasIndexRoute
}

const DashboardCamerasRouteChildren: DashboardCamerasRouteChildren = {
  DashboardCamerasLiveRoute: DashboardCamerasLiveRoute,
  DashboardCamerasIndexRoute: DashboardCamerasIndexRoute,
}

const DashboardCamerasRouteWithChildren =
  DashboardCamerasRoute._addFileChildren(DashboardCamerasRouteChildren)

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardAlertsRoute: typeof DashboardAlertsRoute
  DashboardCamerasRoute: typeof DashboardCamerasRouteWithChildren
  DashboardEmployeesRoute: typeof DashboardEmployeesRoute
  DashboardFaceTrainingRoute: typeof DashboardFaceTrainingRoute
  DashboardHomeRoute: typeof DashboardHomeRoute
  DashboardPresenceRoute: typeof DashboardPresenceRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardRequestsRoute: typeof DashboardRequestsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardUnknownFacesRoute: typeof DashboardUnknownFacesRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardAlertsRoute: DashboardAlertsRoute,
  DashboardCamerasRoute: DashboardCamerasRouteWithChildren,
  DashboardEmployeesRoute: DashboardEmployeesRoute,
  DashboardFaceTrainingRoute: DashboardFaceTrainingRoute,
  DashboardHomeRoute: DashboardHomeRoute,
  DashboardPresenceRoute: DashboardPresenceRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardRequestsRoute: DashboardRequestsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardUnknownFacesRoute: DashboardUnknownFacesRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface LoginRouteChildren {
  LoginAdminRoute: typeof LoginAdminRoute
  LoginHrRoute: typeof LoginHrRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginAdminRoute: LoginAdminRoute,
  LoginHrRoute: LoginHrRoute,
  LoginIndexRoute: LoginIndexRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
